#!/bin/sh

# ~/.fehbg &
hsetroot -solid "#282828" &
blueman-applet &
nm-applet &
$HOME/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# gentoo
/usr/libexec/polkit-gnome-authentication-agent-1 &
xmodmap -e "keysym Alt_R = Multi_key" &
# xss-lock -- /usr/bin/betterlockscreen -l blur &
st -c scratchterm &
st -c dropdowncalc -e "python3" &
monitorconfig &
xcompmgr &

bspc rule -a dropdowncalc sticky=on state=floating hidden=on center=true
bspc rule -a scratchterm sticky=on state=floating hidden=on center=true

wmname LG3D

export PIDSWALLOW_SWALLOW_COMMAND='bspc node $pwid --flag hidden=on'
export PIDSWALLOW_VOMIT_COMMAND='bspc node $pwid --flag hidden=off'
export PIDSWALLOW_PREGLUE_HOOK='bspc query -N -n $pwid.floating >/dev/null && bspc node $cwid --state floating'
pgrep -fl 'pidswallow -gl' || pidswallow -gl &


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
# bspc config top_padding		37
bspc config border_width         2
bspc config window_gap          12
bspc config presel_feedback_color "#ebdbb2"

bspc config normal_border_color "#928374"
bspc config active_border_color
bspc config focused_border_color "#EBDBB2"

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Surf state=tiled
bspc rule -a guvcview state=floating
bspc rule -a Guvcview state=floating
